### ISSUE TITLE
Learn property graphs

### ISSUE THREAD

**Issue by xamde** [Calpano/graphinout#1]

**Comment by xamde** [comment]
[ ] http://graphdatamodeling.com/Graph%20Data%20Modeling/GraphDataModeling/page/PropertyGraphs.html
Wikipedia has no entry on property graphs.

**Comment by rasBab** [comment]
Project challenges
1.	Unmarshalling different types of XML
1.1.	The difference in structure
Because different files have different structures, it is not possible to have a consistent pattern for all of them. To solve this problem, we need to use one of the following methods.

•	Dynamic structure
Dynamic coding methods are inherently complex and there is a need to provide very strong methods for documenting and describing the structure, which is usually very expensive.
One of the important requirements of this method is having the xsd file and mapping it to the internal structure.

•	Static structure
It is an efficient method, but it needs to be very strong, and the use of appropriate design patterns in creating these structures is very important (Method factory, Strategy, Prototype, Proxy,) vital to avoid the spaghetti code.

•	Semi-dynamic structure
The combination of the above two methods can be the best option. But determining the border between the two is almost a matter of taste and a strong agreement should be made to avoid excesses in each part and at the same time provide all the capabilities of both methods.

1.2.	Nested tree structures
The presence of repeated internal tree structures can be very expensive in processing files and sometimes cause errors. None of the stated dynamic or static methods can guarantee that these problems will not occur. Therefore, it is very important to make the necessary arrangements in the design and validation of these structures.

1.3.	Differences in data type with the same concept
The existence of different structures with the same data concept is present in almost all XML structures and is unavoidable, but creating a mapping model concept between different inputs and the internal structure can create confidence for the validation and processing of these values.
2.	Create an internal structure
2.1.	Performance
An internal general structure that can support all the output models at once will probably have a complex structure, and on the other hand, a large amount of data can cause problems with processing or production efficiency. Creating methods such as parallelization or file transfer to different structures to process the data can give better functionality to this structure.
This problem exists in reading and validating and even writing these objects.


2.2.	Maintenance
Storage of files and produced objects should be determined from the point of view of the place of storage, the storage period and the storage method. Because the lifespan of the files and the access rules to these files can be challenging. Therefore, these arrangements should be specified even if they do not need to be applied in the initial phases of the system.

2.3.	Development
The development of any system and structure is one of the inevitable aspects of any live software system. Considering that the main nature of this system is the integration of data structure, it is necessary to create version control methods to prevent the errors of the previous versions and with this method create a legal structure to develop and change the internal structure again.

Proposed initial model

In this model:
1.	The method of processing input files is a semi-static one, which needs to specify the XSD structure of the said file.
2.	There is an XML mapping model on the side of the system to map common concepts with different titles.
3.	Validation for the structure.
4.	Validation for each value.
5.	There is a main converter class that covers various types of inputs as a proxy with a method-factor combination.
6.	The output of this proxy is an object of GioGraphML. which can reach different output models by using a decoder pattern.

**Comment by xamde** [comment]
Hi, this seems to be a rather lengthy discussion not entirely related to the issue at hand. I'll discuss it on our slack channel, ok?
