### ISSUE TITLE
Merge GioEdge into GioHyperEdge

### ISSUE THREAD

**Issue by xamde** [Calpano/graphinout#16]

**Comment by xamde** [comment]
Note how these two pieces encode the exact same graph part:

```
<edge id="id--edge-4S6N" source="id--node4" sourceport="South" target="id--node6" targetport="North"/>
```
 
```
<hyperedge id="id--edge-4S6N">
  <endpoint node="id--node4" type="in" port="South" />
  <endpoint node="id--node6" type="out" port="North" />
</hyperedge>
```

**Comment by rasBab** [comment]
It is possible to add data in the Edge structure.
To convert it to Hyperedge, this element must be added in the Hyperedge structure.
In the documentary GraphML this feature is not stated.
Approach

1. don't convert Edge with data element to Hyperedge.
2. deviate from the standard and add this element to Hyperedge.
3. add data to the endpoint.

<edge directed="false" source="s1" target="t2"><data key="type">undirected</data></edge>
<hyperedge>
       <endpoint node="n3"/>
       <endpoint node="n4"/>
       <endpoint node="n5"/>
       <endpoint node="n6"/>
</hyperedge>

Problems

1. In the first case, because it is a passive method, it eliminates the possibility of producing stream output. Because its information cannot be sent to the output until the end of the entire edge processing.
2. In the second and third method, we deviate from the standard.

**Comment by rasBab** [comment]
#
<edge directed="false" source="s1" target="t2"><data key="type">undirected</data></edge>
<hyperedge>
       <endpoint node="n3"/>
       <endpoint node="n4"/>
       <endpoint node="n5"/>
       <endpoint node="n6"/>
     </hyperedge>

**Comment by xamde** [comment]
hyperedges have endpoint  type=in|out|undir
undir = undirected

An undirected edge has two undirected endpoints.
